CREATE USER genughaben PASSWORD 'docker';
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO genughaben;
ALTER USER genughaben CREATEDB;
CREATE DATABASE dummy;
\c dummy
CREATE TABLE test (id SERIAL PRIMARY KEY, value VARCHAR);